name: Deploy Nightly

on:
  schedule:
    - cron: 15 14 * * *

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4

      - name: install dependencies
        run: npm ci
      - name: generate repository json "db"
        run: node tools/generate-repository-json.mjs
      - name: build release code
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          folder: build/
          branch: gh-pages


